name: Trigger auto deployment for jadci-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/jadci-container-app-AutoDeployTrigger-e3795f84-b4dc-40cf-833d-a48e693391c1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: stensjadciregistry.azurecr.io
          username: ${{ secrets.JADCICONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.JADCICONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stensjadciregistry.azurecr.io/jadci-nodejsapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JADCICONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n jadci-container-app -g container-app --server stensjadciregistry.azurecr.io --username  ${{ secrets.JADCICONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.JADCICONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n jadci-container-app -g container-app --image stensjadciregistry.azurecr.io/jadci-nodejsapp:${{ github.sha }}
