name: Trigger auto deployment for stens-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/stens-container-app-AutoDeployTrigger-f67311f5-e738-46b9-864a-b20a81dbab4b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: stenscontainerregistry.azurecr.io
          username: ${{ secrets.STENSCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.STENSCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stenscontainerregistry.azurecr.io/stens-container-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.STENSCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n stens-container-app -g container-app --server stenscontainerregistry.azurecr.io --username  ${{ secrets.STENSCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.STENSCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n stens-container-app -g container-app --image stenscontainerregistry.azurecr.io/stens-container-app:${{ github.sha }}
