name: Trigger auto deployment for yarbleydemoapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/yarbleydemoapp-AutoDeployTrigger-cb3b6512-6f70-4329-909d-b550d6aef9c9.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: yarbleyappdemo.azurecr.io
          username: ${{ secrets.YARBLEYDEMOAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.YARBLEYDEMOAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yarbleyappdemo.azurecr.io/demo-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.YARBLEYDEMOAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n yarbleydemoapp -g appdemo --server yarbleyappdemo.azurecr.io --username  ${{ secrets.YARBLEYDEMOAPP_REGISTRY_USERNAME }} --password ${{ secrets.YARBLEYDEMOAPP_REGISTRY_PASSWORD }}
            az containerapp update -n yarbleydemoapp -g appdemo --image yarbleyappdemo.azurecr.io/demo-app:${{ github.sha }}
